name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: '2.176/Dockerfile'
            tags: [ "zyuzka/jenkins:2.176" ]
            platforms: ['linux/amd64', 'linux/arm64']
          - image: '2.305/Dockerfile'
            tags: [ "zyuzka/jenkins:2.305" ]
            platforms: ['linux/amd64', 'linux/arm64']
          - image: '2.324/Dockerfile'
            tags: [ "zyuzka/jenkins:latest", "zyuzka/jenkins:2.324" ]
            platforms: [ 'linux/amd64', 'linux/arm64' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Binfmt run
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
#          push: true
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platforms) }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
