name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORGA: 'zyuzka'
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: '2.176/Dockerfile'
            tags: [ "$ORGA/jenkins:2.176" ]
          - image: '2.305/Dockerfile'
            tags: [ "$ORGA/jenkins:latest", "$ORGA/jenkins:2.305" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: linux/amd64,linux/arm64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
